name: Auto Accept Collabs

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Auto Accept Collabs
        uses: kbrashears5/github-action-auto-accept-collabs@1.0.1
        with:
          TOKEN: ${{ secrets.ACTIONS }}
